import { Donation, User } from "./types";

export const areas = [
    "No Poverty",
    "Gender Equality",
    "Help Elders",
    "Zero Hunger",
    "Good Health and Well Being",
    "Clean Water",
    "Reduced Trash",
];

export const donationData: Donation[] = [
    {
        image: "https://via.placeholder.com/40",
        title: "Rebuild Homes for Disaster Victims",
        tag: "Emergency Relief",
        about: "This is a detailed description of the Rebuild Homes for Disaster Victims campaign. It focuses on providing emergency relief to communities affected by natural disasters. The campaign aims to supply essential items such as food, water, and medical supplies to those in need. Immediate assistance is crucial to help these communities recover and rebuild their lives. Donations will be used to ensure timely and effective distribution of aid.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 5471,
        amountNeeded: 15754,
        reasonForSeekingDonation: "To provide emergency relief to disaster-affected areas.",
        daysLeft: 41,
        donationAreas: ["Gender Equality", "Help Elders", "Good Health and Well Being"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Support Education for Girls focuses on providing educational resources",
        tag: "Trending",
        about: "This is a detailed description of the Support Education for Girls campaign. The campaign focuses on providing educational resources and support for girls in underprivileged areas. Funds will be used to purchase school supplies, provide scholarships, and support educational programs. Education is a fundamental right, and empowering girls through education can lead to significant social and economic benefits. Your donation will help ensure that girls have access to quality education and opportunities for a brighter future.",
        type: "Charity",
        gender: "Female",
        totalDonatedAmount: 5000,
        amountNeeded: 10000,
        reasonForSeekingDonation: "To provide educational resources and support for girls in underprivileged areas.",
        daysLeft: 30,
        donationAreas: ["Gender Equality", "Good Health and Well Being", "No Poverty"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Scholarships for Underprivileged Children",
        tag: "Education",
        about: "This is a detailed description of the Scholarships for Underprivileged Children campaign. The campaign is dedicated to improving educational opportunities for underprivileged children. Funds will be used to provide scholarships, school supplies, and educational materials to children in need. By supporting this campaign, you are helping to break the cycle of poverty and provide children with the tools they need to succeed in life. Education is a powerful tool for social change, and your contribution can make a significant impact.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 7679,
        amountNeeded: 17541,
        reasonForSeekingDonation: "To improve educational opportunities for underprivileged children.",
        daysLeft: 85,
        donationAreas: ["Zero Hunger", "Reduced Trash"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Medical Aid for Rural Areas",
        tag: "Medical Aid",
        about: "This is a detailed description of the Medical Aid for Rural Areas campaign. The campaign aims to provide essential medical supplies and healthcare services to rural communities that lack access to adequate medical care. Funds will be used to purchase medical equipment, medicines, and to support medical personnel who travel to these remote areas. Your donation will help save lives and improve the health and well-being of people living in rural areas.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 6411,
        amountNeeded: 14053,
        reasonForSeekingDonation: "To provide essential medical supplies and healthcare services to rural communities.",
        daysLeft: 61,
        donationAreas: ["No Poverty", "Help Elders", "Clean Water"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Clean Water for Every Child",
        tag: "Trending",
        about: "This is a detailed description of the Clean Water for Every Child campaign. The campaign focuses on providing clean and safe drinking water to children in underserved communities. Funds will be used to install water purification systems, build wells, and provide water storage solutions. Access to clean water is essential for good health and can prevent waterborne diseases. Your support will help ensure that every child has access to this basic necessity.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 9250,
        amountNeeded: 20000,
        reasonForSeekingDonation: "To provide clean and safe drinking water to children in underserved communities.",
        daysLeft: 50,
        donationAreas: ["Clean Water", "Good Health and Well Being", "Zero Hunger"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Support for Homeless Veterans",
        tag: "Trending",
        about: "This is a detailed description of the Support for Homeless Veterans campaign. The campaign aims to provide housing, job training, and mental health support for homeless veterans. Funds will be used to offer temporary shelters, vocational training programs, and counseling services. Our veterans have sacrificed so much for our country, and it is our duty to support them in their time of need. Your donation will help improve their quality of life and provide them with the support they deserve.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 11000,
        amountNeeded: 25000,
        reasonForSeekingDonation: "To provide housing, job training, and mental health support for homeless veterans.",
        daysLeft: 30,
        donationAreas: ["No Poverty", "Good Health and Well Being", "Gender Equality"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Food Security for Families",
        tag: "Zero Hunger",
        about: "This is a detailed description of the Food Security for Families campaign. The campaign focuses on ensuring that families in need have access to nutritious food. Funds will be used to purchase and distribute food supplies, support community kitchens, and run food assistance programs. Food security is a fundamental human right, and your contribution will help fight hunger and ensure that families do not go to bed hungry.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 8000,
        amountNeeded: 18000,
        reasonForSeekingDonation: "To ensure that families in need have access to nutritious food.",
        daysLeft: 70,
        donationAreas: ["Zero Hunger", "Good Health and Well Being", "Reduced Trash"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Empowering Women Entrepreneurs",
        tag: "Gender Equality",
        about: "This is a detailed description of the Empowering Women Entrepreneurs campaign. The campaign aims to support women entrepreneurs by providing them with micro-loans, business training, and mentorship programs. Funds will be used to create financial opportunities for women, helping them to start and grow their businesses. Empowering women economically leads to stronger communities and fosters gender equality. Your donation will help women achieve their entrepreneurial dreams and contribute to economic growth.",
        type: "Charity",
        gender: "Female",
        totalDonatedAmount: 9500,
        amountNeeded: 20000,
        reasonForSeekingDonation: "To support women entrepreneurs with micro-loans, business training, and mentorship programs.",
        daysLeft: 60,
        donationAreas: ["Gender Equality", "No Poverty", "Good Health and Well Being"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Healthcare for Children with Disabilities",
        tag: "Trending",
        about: "This is a detailed description of the Healthcare for Children with Disabilities campaign. The campaign focuses on providing specialized medical care and therapy for children with disabilities. Funds will be used to support medical treatments, rehabilitation programs, and the purchase of adaptive equipment. Children with disabilities deserve access to the best possible care to improve their quality of life. Your donation will help these children lead healthier and more fulfilling lives.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 12000,
        amountNeeded: 25000,
        reasonForSeekingDonation: "To provide specialized medical care and therapy for children with disabilities.",
        daysLeft: 45,
        donationAreas: ["Good Health and Well Being", "Help Elders", "Clean Water"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Clean Energy for Rural Schools",
        tag: "Sustainable Development",
        about: "This is a detailed description of the Clean Energy for Rural Schools campaign. The campaign aims to provide clean and renewable energy solutions for schools in rural areas. Funds will be used to install solar panels, provide energy-efficient lighting, and create sustainable energy systems. Access to clean energy will improve the learning environment and reduce the carbon footprint. Your donation will help create a sustainable future for these communities.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 10000,
        amountNeeded: 22000,
        reasonForSeekingDonation: "To provide clean and renewable energy solutions for schools in rural areas.",
        daysLeft: 90,
        donationAreas: ["Clean Water", "Reduced Trash", "Good Health and Well Being"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Support for Refugee Families",
        tag: "Humanitarian Aid",
        about: "This is a detailed description of the Support for Refugee Families campaign. The campaign focuses on providing essential aid to refugee families who have been displaced due to conflict and persecution. Funds will be used to supply food, shelter, medical care, and educational opportunities. Refugees often face immense challenges, and your support can help provide them with the basic necessities and hope for a better future. Your donation will make a significant difference in the lives of these vulnerable families.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 8500,
        amountNeeded: 20000,
        reasonForSeekingDonation: "To provide essential aid to refugee families displaced due to conflict and persecution.",
        daysLeft: 55,
        donationAreas: ["No Poverty", "Zero Hunger", "Clean Water"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Support for Orphaned Children",
        tag: "Children's Aid",
        about: "This is a detailed description of the Support for Orphaned Children campaign. The campaign aims to provide comprehensive support for orphaned children, including shelter, education, and emotional care. Funds will be used to maintain orphanages, provide educational scholarships, and offer counseling services. Every child deserves a loving and supportive environment, and your donation will help ensure that orphaned children receive the care and opportunities they need to thrive.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 6000,
        amountNeeded: 15000,
        reasonForSeekingDonation: "To provide comprehensive support for orphaned children.",
        daysLeft: 40,
        donationAreas: ["Good Health and Well Being", "Gender Equality", "No Poverty"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Animal Shelter Renovation",
        tag: "Animal Welfare",
        about: "This is a detailed description of the Animal Shelter Renovation campaign. The campaign focuses on renovating and improving the facilities at a local animal shelter. Funds will be used to upgrade kennels, purchase medical supplies, and improve living conditions for the animals. Animal shelters play a crucial role in caring for abandoned and stray animals. Your donation will help provide a safe and comfortable environment for these animals as they await adoption.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 5000,
        amountNeeded: 12000,
        reasonForSeekingDonation: "To renovate and improve the facilities at a local animal shelter.",
        daysLeft: 35,
        donationAreas: ["Reduced Trash", "Clean Water", "Good Health and Well Being"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Feeding Homeless Youth",
        tag: "Zero Hunger",
        about: "This is a detailed description of the Feeding Homeless Youth campaign. The campaign aims to provide nutritious meals to homeless youth living on the streets. Funds will be used to operate mobile food trucks, establish soup kitchens, and distribute food packages. Homeless youth often face food insecurity, and your support can help ensure they have access to healthy meals. Your donation will help fight hunger and provide hope to these vulnerable young individuals.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 7000,
        amountNeeded: 15000,
        reasonForSeekingDonation: "To provide nutritious meals to homeless youth living on the streets.",
        daysLeft: 25,
        donationAreas: ["Zero Hunger", "Good Health and Well Being", "Reduced Trash"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Senior Citizen Care Program",
        tag: "Help Elders",
        about: "This is a detailed description of the Senior Citizen Care Program campaign. The campaign focuses on providing comprehensive care and support for senior citizens. Funds will be used to offer healthcare services, recreational activities, and social support programs. Senior citizens often face isolation and health challenges, and your donation can help improve their quality of life. Your support will provide the care and companionship they need to enjoy their golden years.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 6500,
        amountNeeded: 16000,
        reasonForSeekingDonation: "To provide comprehensive care and support for senior citizens.",
        daysLeft: 60,
        donationAreas: ["Help Elders", "Good Health and Well Being", "Clean Water"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Environmental Cleanup Initiative",
        tag: "Environmental",
        about: "This is a detailed description of the Environmental Cleanup Initiative campaign. The campaign aims to organize community clean-up events to remove trash and pollutants from local parks, rivers, and beaches. Funds will be used to purchase cleaning supplies, organize volunteer efforts, and raise awareness about environmental conservation. A clean environment is essential for public health and the well-being of our planet. Your donation will help keep our natural spaces clean and beautiful for everyone to enjoy.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 4800,
        amountNeeded: 10000,
        reasonForSeekingDonation: "To organize community clean-up events and remove trash and pollutants from local areas.",
        daysLeft: 45,
        donationAreas: ["Reduced Trash", "Clean Water", "Good Health and Well Being"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Job Training for Unemployed Youth",
        tag: "Employment",
        about: "This is a detailed description of the Job Training for Unemployed Youth campaign. The campaign focuses on providing job training and employment opportunities for young people who are unemployed. Funds will be used to offer vocational training programs, apprenticeship opportunities, and job placement services. Helping young people gain the skills they need to secure employment is essential for their future success. Your donation will support programs that empower youth and reduce unemployment.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 7500,
        amountNeeded: 17000,
        reasonForSeekingDonation: "To provide job training and employment opportunities for young people who are unemployed.",
        daysLeft: 75,
        donationAreas: ["No Poverty", "Gender Equality", "Good Health and Well Being"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Mental Health Support for Teens",
        tag: "Mental Health",
        about: "This is a detailed description of the Mental Health Support for Teens campaign. The campaign aims to provide mental health support and counseling services for teenagers struggling with mental health issues. Funds will be used to offer therapy sessions, create support groups, and run mental health awareness programs. Mental health is a critical aspect of overall well-being, and early intervention can make a significant difference. Your donation will help provide the necessary support for teens to lead healthy and fulfilling lives.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 6800,
        amountNeeded: 15000,
        reasonForSeekingDonation: "To provide mental health support and counseling services for teenagers.",
        daysLeft: 50,
        donationAreas: ["Good Health and Well Being", "Gender Equality", "No Poverty"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Building Schools in Rural Africa",
        tag: "Education",
        about: "This is a detailed description of the Building Schools in Rural Africa campaign. The campaign focuses on constructing schools and improving educational infrastructure in rural African communities. Funds will be used to build classrooms, provide educational materials, and train teachers. Education is a key factor in breaking the cycle of poverty and promoting economic development. Your donation will help provide children in rural Africa with access to quality education and a brighter future.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 10000,
        amountNeeded: 25000,
        reasonForSeekingDonation: "To construct schools and improve educational infrastructure in rural African communities.",
        daysLeft: 90,
        donationAreas: ["No Poverty", "Zero Hunger", "Gender Equality"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Support for Victims of Domestic Violence",
        tag: "Support",
        about: "This is a detailed description of the Support for Victims of Domestic Violence campaign. The campaign aims to provide support and resources for individuals affected by domestic violence. Funds will be used to offer safe shelters, counseling services, and legal assistance. Domestic violence has a profound impact on victims' lives, and your support can help them find safety and rebuild their lives. Your donation will provide the necessary support for victims to escape abusive situations and start anew.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 8500,
        amountNeeded: 20000,
        reasonForSeekingDonation: "To provide support and resources for individuals affected by domestic violence.",
        daysLeft: 65,
        donationAreas: ["Gender Equality", "Good Health and Well Being", "No Poverty"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Disaster Preparedness Education",
        tag: "Education",
        about: "This is a detailed description of the Disaster Preparedness Education campaign. The campaign focuses on educating communities about disaster preparedness and resilience. Funds will be used to create educational materials, conduct training workshops, and develop emergency response plans. Being prepared for disasters can save lives and reduce the impact of emergencies. Your donation will help equip communities with the knowledge and resources they need to stay safe during disasters.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 4000,
        amountNeeded: 10000,
        reasonForSeekingDonation: "To educate communities about disaster preparedness and resilience.",
        daysLeft: 30,
        donationAreas: ["Good Health and Well Being", "No Poverty", "Clean Water"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Clean Water Initiative for Rural Villages",
        tag: "Clean Water",
        about: "This is a detailed description of the Clean Water Initiative for Rural Villages campaign. The campaign aims to provide clean and safe drinking water to rural villages lacking access to clean water sources. Funds will be used to install water filtration systems, build wells, and develop sustainable water management practices. Access to clean water is vital for health and well-being. Your donation will help ensure that rural villagers have access to this essential resource, improving their quality of life.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 9000,
        amountNeeded: 20000,
        reasonForSeekingDonation: "To provide clean and safe drinking water to rural villages.",
        daysLeft: 60,
        donationAreas: ["Clean Water", "Good Health and Well Being", "No Poverty"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Child Nutrition Program",
        tag: "Zero Hunger",
        about: "This is a detailed description of the Child Nutrition Program campaign. The campaign focuses on providing nutritious meals and nutritional education to children in need. Funds will be used to support school feeding programs, distribute food packages, and conduct nutritional workshops. Proper nutrition is crucial for children's growth and development. Your donation will help ensure that children receive the nourishment they need to thrive and reach their full potential.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 7800,
        amountNeeded: 17000,
        reasonForSeekingDonation: "To provide nutritious meals and nutritional education to children in need.",
        daysLeft: 50,
        donationAreas: ["Zero Hunger", "Good Health and Well Being", "Clean Water"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Youth Sports Program",
        tag: "Recreation",
        about: "This is a detailed description of the Youth Sports Program campaign. The campaign aims to provide recreational opportunities and promote physical activity among young people. Funds will be used to organize sports leagues, purchase equipment, and create safe play spaces. Participation in sports can improve physical health, build teamwork skills, and boost self-esteem. Your donation will help create positive experiences for youth through sports and recreational activities.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 6500,
        amountNeeded: 15000,
        reasonForSeekingDonation: "To provide recreational opportunities and promote physical activity among young people.",
        daysLeft: 40,
        donationAreas: ["Good Health and Well Being", "Gender Equality", "No Poverty"],
    }, {
        image: "https://via.placeholder.com/40",
        title: "Support for Mental Health Initiatives",
        tag: "Trending",
        about: "This campaign aims to provide resources for mental health services, including therapy sessions, community workshops, and awareness programs. Your support will help destigmatize mental health issues and improve access to care.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 9000,
        amountNeeded: 25000,
        reasonForSeekingDonation: "To enhance mental health support in communities.",
        daysLeft: 30,
        donationAreas: ["Good Health and Well Being", "Reduced Inequalities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Advocating for Climate Action",
        tag: "Trending",
        about: "This initiative focuses on advocating for climate change awareness and action through community engagement, educational programs, and local projects. Funds will be used for campaigns that promote sustainable practices.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 12000,
        amountNeeded: 35000,
        reasonForSeekingDonation: "To drive local and global climate action efforts.",
        daysLeft: 40,
        donationAreas: ["Climate Action", "Sustainable Cities and Communities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Youth Empowerment Through Sports",
        tag: "Trending",
        about: "This campaign provides sports training and mentorship for at-risk youth, focusing on teamwork, discipline, and leadership skills. Your contributions will fund coaching sessions, equipment, and tournaments.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 8000,
        amountNeeded: 20000,
        reasonForSeekingDonation: "To empower youth through sports and recreation.",
        daysLeft: 50,
        donationAreas: ["Good Health and Well Being", "Quality Education"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Access to Clean Energy Solutions",
        tag: "Trending",
        about: "This initiative aims to provide solar energy solutions to low-income households. Funds will be used to install solar panels, provide training, and support community-led energy projects.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 15000,
        amountNeeded: 50000,
        reasonForSeekingDonation: "To promote renewable energy access in underserved communities.",
        daysLeft: 70,
        donationAreas: ["Affordable and Clean Energy", "Sustainable Development"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Restoration of Endangered Habitats",
        tag: "Trending",
        about: "This campaign focuses on restoring natural habitats that support endangered species. Funds will be used for reforestation efforts, habitat protection, and community awareness initiatives.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 5000,
        amountNeeded: 15000,
        reasonForSeekingDonation: "To protect biodiversity and restore ecosystems.",
        daysLeft: 55,
        donationAreas: ["Life on Land", "Climate Action"],
    }, {
        image: "https://via.placeholder.com/40",
        title: "Support for Refugee Families",
        tag: "Trending",
        about: "This campaign aims to provide essential supplies and support for refugee families, including housing assistance, education resources, and healthcare services. Your donation will help provide a safe and stable environment.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 11000,
        amountNeeded: 30000,
        reasonForSeekingDonation: "To assist refugees in building new lives.",
        daysLeft: 25,
        donationAreas: ["No Poverty", "Reduced Inequalities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Animal Welfare Education Programs",
        tag: "Trending",
        about: "This initiative focuses on educating communities about responsible pet ownership and wildlife conservation. Funds will be used for workshops, educational materials, and community outreach efforts.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 4000,
        amountNeeded: 12000,
        reasonForSeekingDonation: "To promote animal welfare and conservation education.",
        daysLeft: 45,
        donationAreas: ["Life Below Water", "Good Health and Well Being"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Digital Literacy for Seniors",
        tag: "Trending",
        about: "This campaign provides digital literacy training for senior citizens, helping them navigate technology and access online resources. Your support will fund classes, materials, and volunteer training.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 6500,
        amountNeeded: 15000,
        reasonForSeekingDonation: "To empower seniors through technology.",
        daysLeft: 60,
        donationAreas: ["Quality Education", "Reduced Inequalities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Healthy Meals for School Children",
        tag: "Trending",
        about: "This initiative aims to provide nutritious meals for children in low-income schools. Funds will be used to source fresh produce and develop meal programs to improve student health and learning.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 9000,
        amountNeeded: 25000,
        reasonForSeekingDonation: "To combat child hunger and promote healthy eating.",
        daysLeft: 35,
        donationAreas: ["Zero Hunger", "Good Health and Well Being"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Community-Based Recycling Initiatives",
        tag: "Trending",
        about: "This campaign focuses on launching community recycling programs to reduce waste and promote sustainability. Funds will be used for educational campaigns, recycling bins, and community workshops.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 3000,
        amountNeeded: 10000,
        reasonForSeekingDonation: "To promote recycling and environmental stewardship.",
        daysLeft: 50,
        donationAreas: ["Sustainable Cities and Communities", "Responsible Consumption and Production"],
    }, {
        image: "https://via.placeholder.com/40",
        title: "Local Artisans Support Fund",
        tag: "Local",
        about: "This campaign aims to support local artisans by providing funds for materials and workshops. Your donations will help keep traditional crafts alive and empower local talent.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 3000,
        amountNeeded: 10000,
        reasonForSeekingDonation: "To support local artisans and preserve cultural heritage.",
        daysLeft: 40,
        donationAreas: ["Decent Work and Economic Growth", "Reduced Inequalities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Community Playground Renovation",
        tag: "Local",
        about: "This initiative focuses on renovating and upgrading community playgrounds to provide safe and engaging spaces for children. Funds will go towards equipment and maintenance.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 5000,
        amountNeeded: 15000,
        reasonForSeekingDonation: "To create safe play spaces for children.",
        daysLeft: 30,
        donationAreas: ["Sustainable Cities and Communities", "Good Health and Well Being"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Local Food Bank Expansion",
        tag: "Local",
        about: "This campaign aims to expand the local food bank services, providing more resources and reach to families in need. Your donations will help stock shelves and distribute food.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 8000,
        amountNeeded: 20000,
        reasonForSeekingDonation: "To alleviate hunger in our community.",
        daysLeft: 20,
        donationAreas: ["Zero Hunger", "No Poverty"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Community Clean-Up Day",
        tag: "Local",
        about: "This initiative organizes community clean-up events to promote environmental awareness and community pride. Funds will be used for supplies and outreach materials.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 1500,
        amountNeeded: 5000,
        reasonForSeekingDonation: "To enhance local environments through community action.",
        daysLeft: 50,
        donationAreas: ["Sustainable Cities and Communities", "Responsible Consumption and Production"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Local Wildlife Habitat Restoration",
        tag: "Local",
        about: "This campaign focuses on restoring local wildlife habitats through planting native vegetation and removing invasive species. Your support will help protect biodiversity in our area.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 7000,
        amountNeeded: 12000,
        reasonForSeekingDonation: "To restore and protect local ecosystems.",
        daysLeft: 45,
        donationAreas: ["Life on Land", "Climate Action"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Support for Local Farmers' Market",
        tag: "Local",
        about: "This initiative aims to support the local farmers' market by funding advertising and infrastructure improvements. Your donation will help promote local agriculture and healthy eating.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 4000,
        amountNeeded: 10000,
        reasonForSeekingDonation: "To support local farmers and promote fresh produce.",
        daysLeft: 30,
        donationAreas: ["Decent Work and Economic Growth", "Good Health and Well Being"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Neighborhood Literacy Programs",
        tag: "Local",
        about: "This campaign focuses on providing literacy resources and classes for adults and children in the community. Funds will be used for materials, tutors, and outreach efforts.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 6000,
        amountNeeded: 15000,
        reasonForSeekingDonation: "To improve literacy rates in our neighborhood.",
        daysLeft: 35,
        donationAreas: ["Quality Education", "Reduced Inequalities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Local Historical Site Preservation",
        tag: "Local",
        about: "This initiative aims to preserve and maintain a local historical site, ensuring it remains a valuable resource for the community. Your donations will fund restoration efforts and educational programs.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 2500,
        amountNeeded: 8000,
        reasonForSeekingDonation: "To preserve our local history for future generations.",
        daysLeft: 55,
        donationAreas: ["Sustainable Cities and Communities", "Reduced Inequalities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Youth Mentorship Program",
        tag: "Local",
        about: "This campaign aims to connect youth with mentors in the community, providing guidance and support for personal and professional development. Funds will be used for training mentors and organizing events.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 3500,
        amountNeeded: 12000,
        reasonForSeekingDonation: "To empower youth through mentorship.",
        daysLeft: 60,
        donationAreas: ["Quality Education", "Reduced Inequalities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Local Health Fair Organization",
        tag: "Local",
        about: "This initiative focuses on organizing a local health fair to provide free health screenings and resources for the community. Your support will help cover costs for services and outreach.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 2000,
        amountNeeded: 6000,
        reasonForSeekingDonation: "To promote health awareness and access to care.",
        daysLeft: 25,
        donationAreas: ["Good Health and Well Being", "No Poverty"],
    }, {
        image: "https://via.placeholder.com/40",
        title: "Global Clean Oceans Initiative",
        tag: "Global",
        about: "This campaign focuses on reducing plastic pollution in our oceans by organizing beach clean-ups and promoting sustainable practices. Your donations will fund cleanup operations and educational programs.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 12000,
        amountNeeded: 30000,
        reasonForSeekingDonation: "To protect marine ecosystems and promote ocean health.",
        daysLeft: 70,
        donationAreas: ["Life Below Water", "Sustainable Cities and Communities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Education for Refugee Children",
        tag: "Global",
        about: "This initiative aims to provide education and resources for children displaced by conflict. Funds will be used for school supplies, teacher training, and creating safe learning environments.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 8000,
        amountNeeded: 25000,
        reasonForSeekingDonation: "To ensure every child has access to education.",
        daysLeft: 50,
        donationAreas: ["Quality Education", "Reduced Inequalities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Global Vaccination Campaign",
        tag: "Global",
        about: "This campaign focuses on increasing access to vaccinations in underserved communities around the world. Your contributions will help fund vaccine distribution and education programs.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 15000,
        amountNeeded: 50000,
        reasonForSeekingDonation: "To combat preventable diseases globally.",
        daysLeft: 90,
        donationAreas: ["Good Health and Well Being", "No Poverty"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Global Reforestation Project",
        tag: "Global",
        about: "This initiative aims to plant millions of trees across the globe to combat climate change and restore habitats. Donations will support tree planting efforts and community engagement.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 10000,
        amountNeeded: 20000,
        reasonForSeekingDonation: "To mitigate climate change and support biodiversity.",
        daysLeft: 75,
        donationAreas: ["Climate Action", "Life on Land"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Global Water Access Initiative",
        tag: "Global",
        about: "This campaign seeks to provide clean drinking water to communities lacking access. Funds will be allocated for well drilling, filtration systems, and community education.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 9000,
        amountNeeded: 30000,
        reasonForSeekingDonation: "To ensure everyone has access to clean water.",
        daysLeft: 65,
        donationAreas: ["Clean Water and Sanitation", "Good Health and Well Being"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Global Climate Change Awareness",
        tag: "Global",
        about: "This initiative focuses on raising awareness about climate change and its impacts. Donations will support campaigns, educational resources, and community workshops.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 6000,
        amountNeeded: 15000,
        reasonForSeekingDonation: "To educate communities about climate change.",
        daysLeft: 40,
        donationAreas: ["Climate Action", "Sustainable Cities and Communities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Global Health Access Initiative",
        tag: "Global",
        about: "This campaign aims to improve healthcare access in low-income countries by funding mobile clinics and training local health workers.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 20000,
        amountNeeded: 60000,
        reasonForSeekingDonation: "To ensure equitable healthcare access worldwide.",
        daysLeft: 100,
        donationAreas: ["Good Health and Well Being", "Reduced Inequalities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Global Renewable Energy Access",
        tag: "Global",
        about: "This initiative focuses on providing renewable energy solutions to communities without electricity. Donations will fund solar panels and energy education programs.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 11000,
        amountNeeded: 25000,
        reasonForSeekingDonation: "To promote sustainable energy access globally.",
        daysLeft: 80,
        donationAreas: ["Affordable and Clean Energy", "Sustainable Cities and Communities"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Global Food Security Program",
        tag: "Global",
        about: "This campaign aims to address food insecurity by supporting sustainable agriculture initiatives and food distribution networks in vulnerable regions.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 7000,
        amountNeeded: 18000,
        reasonForSeekingDonation: "To promote food security and reduce hunger.",
        daysLeft: 55,
        donationAreas: ["Zero Hunger", "Sustainable Agriculture"],
    },
    {
        image: "https://via.placeholder.com/40",
        title: "Global Gender Equality Campaign",
        tag: "Global",
        about: "This initiative focuses on promoting gender equality through advocacy, education, and empowerment programs. Donations will support grassroots organizations and awareness campaigns.",
        type: "Charity",
        gender: "All",
        totalDonatedAmount: 5000,
        amountNeeded: 15000,
        reasonForSeekingDonation: "To advance gender equality worldwide.",
        daysLeft: 45,
        donationAreas: ["Gender Equality", "Reduced Inequalities"],
    },
];

export const users: User[] = [
    {
        userId: "1",
        firstName: "John",
        lastName: "Doe",
        totalDonated: 150,
        totalPeopleHelped: 10,
        email: "john.doe@example.com",
        password: "password123"
    },
    {
        userId: "2",
        firstName: "Jane",
        lastName: "Smith",
        totalDonated: 300,
        totalPeopleHelped: 20,
        email: "jane.smith@example.com",
        password: "password456"
    },
    {
        userId: "3",
        firstName: "Alice",
        lastName: "Johnson",
        totalDonated: 250,
        totalPeopleHelped: 15,
        email: "alice.johnson@example.com",
        password: "password789"
    },
];